name: PR Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Setup terraform-backend-git
        uses: plumber-cd/setup-terraform-backend-git@v1
        with:
          version:
            0.1.2
      - name: Use command
        run: terraform-backend-git version
