name: PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup terraform-backend-git
        uses: plumber-cd/terraform-backend-git@master
        with:
          version: v0.1.2
      - name: Use command
        run: terraform-backend-git version
